### ISSUE TITLE
Yotpo integration has been failing to update majority of tables.

### ISSUE THREAD

**Issue by tmann201** [singer-io/tap-yotpo#54]
Only product_reviews and product_reviews__images_data are updating. All other tables have gone stale since June 2021.

Logs contain the following error:
HTTP-error-code: 404, Error: No route matches [GET] "/v1/widget/......................................../products/1.94967E+12/reviews.json"

**Comment by sgandhi1311** [comment]
Hello @tmann201 
The Yotpo API endpoint will not allow any special characters (except **_** and **-**) while hitting the product review endpoint. Refer to doc - [link](https://apidocs.yotpo.com/reference/retrieve-reviews-for-a-product)
In your case, the `external_product_id` - 1.94967E+12 contains the special character - `+`.
We need to skip the retrieval of product reviews for that specific product_id in this scenario. Yotpo and stitch has no role in updating the external_product_id, customer should update there store product_id with no special characters in it.
Please upgrade tap version from 1.3.6 to 2.0.0. It will skip to retrieve the response from API endpoints with the log message.

**Comment by tmann201** [comment]
@sgandhi1311 thank you so much for the reply! What's the best way to upgrade the tap version? If I delete and recreate the integration, can it seamlessly resume syncing to my existing target schema? (Sorry, I am new to using Stitch).

**Comment by sgandhi1311** [comment]
I will suggest you create a new connection with the new name.
The reason is - Yotpo has upgraded the API version from v1 to v3. The response for the v3 endpoints differs in some cases compared to an earlier version. for eg - For products endpoint, earlier we used to get `id` in response, in version v3 we get `yotpo_id` in the response. So the primary key naming has been changed.

Reference - 
Yotpo doc - https://core-api.yotpo.com/reference/retrieve-products
Stitch doc regarding destination schema - https://www.stitchdata.com/docs/replication/loading/understanding-destination-schemas
